### ISSUE TITLE
Please provide to Releases the archive with deps

### ISSUE THREAD

**Issue by vitaly-zdanevich** [dshills/termai#2]
Because to add this software to Gentoo Linux package manager - we need to fetch vendored deps from somewhere.

**Comment by dshills** [comment]
I'm sorry, I'm not sure what you're asking for. The go.mod file lists all external dependencies and they can be downloaded using `go mod download`.

**Comment by vitaly-zdanevich** [comment]
Yes but in Gentoo Linux packages installing without internet access :(

We cannot use `go mod download` in Gentoo ebuilds :(

**Comment by dshills** [comment]
Ahhh, now I get you. I'll put together a release and/or a vendor directory
